AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A basic SAM Template for Slots and Bookings API.
Resources:
  SlotsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Slots
      AttributeDefinitions:
      - AttributeName: slotId
        AttributeType: S
      KeySchema:
      - AttributeName: slotId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    Metadata:
      SamResourceId: SlotsTable
  BookingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Bookings
      AttributeDefinitions:
      - AttributeName: bookingId
        AttributeType: N
      KeySchema:
      - AttributeName: bookingId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    Metadata:
      SamResourceId: BookingsTable
  SlotsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://car-wash-bot-project/12cb5133a8d0d775dda0f59aa992fd01
      Handler: app.handler
      Runtime: nodejs14.x
      Events:
        GetSlots:
          Type: Api
          Properties:
            Path: /slots
            Method: get
    Metadata:
      SamResourceId: SlotsFunction
  BookingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://car-wash-bot-project/8f821ad9cd332477b96d6d81863c5424
      Handler: app.handler
      Runtime: nodejs14.x
      Events:
        CreateBooking:
          Type: Api
          Properties:
            Path: /booking
            Method: post
    Metadata:
      SamResourceId: BookingsFunction
  AddSlotsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://car-wash-bot-project/d6f9004403e2f7c1213fa282b0ebb7b0
      Handler: app.handler
      Runtime: nodejs14.x
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        CreateSlot:
          Type: Api
          Properties:
            Path: /addSlot
            Method: post
    Metadata:
      SamResourceId: AddSlotsFunction
  AutoAddSlotsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://car-wash-bot-project/e787762bec6e4fdc67c51ac52764ed9d
      Handler: app.handler
      Runtime: nodejs14.x
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        CreateAutoAddSlot:
          Type: Api
          Properties:
            Path: /autoAddSlots
            Method: post
    Metadata:
      SamResourceId: AutoAddSlotsFunction
  API:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: '2.0'
        info:
          title: Slots and Bookings API
          version: '1.0'
        paths:
          /slots:
            get:
              x-amazon-apigateway-integration:
                type: aws_proxy
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SlotsFunction.Arn}/invocations
          /booking:
            post:
              x-amazon-apigateway-integration:
                type: aws_proxy
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BookingsFunction.Arn}/invocations
          /addSlot:
            post:
              x-amazon-apigateway-integration:
                type: aws_proxy
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AddSlotsFunction.Arn}/invocations
          /autoAddSlots:
            post:
              x-amazon-apigateway-integration:
                type: aws_proxy
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AutoAddSlotsFunction.Arn}/invocations
    Metadata:
      SamResourceId: API
Outputs:
  SlotsApi:
    Description: API Gateway endpoint URL for Prod environment for Slots function
    Value:
      Fn::Sub: https://${API}.execute-api.${AWS::Region}.amazonaws.com/Prod/slots/
  BookingsApi:
    Description: API Gateway endpoint URL for Prod environment for Bookings function
    Value:
      Fn::Sub: https://${API}.execute-api.${AWS::Region}.amazonaws.com/Prod/booking/
  AddSlotsApi:
    Description: API Gateway endpoint URL for Prod environment for AddSlots function
    Value:
      Fn::Sub: https://${API}.execute-api.${AWS::Region}.amazonaws.com/Prod/addSlot/
  AutoAddSlotsApi:
    Description: API Gateway endpoint URL for Prod environment for AutoAddSlots function
    Value:
      Fn::Sub: https://${API}.execute-api.${AWS::Region}.amazonaws.com/Prod/autoAddSlots/
